// Shader functions and presets

export const shaderFunctions = [
  '// Simplex 3D Noise',
  '// https://gist.github.com/patriciogonzalezvivo/670c22f3966e662d2f83',
  'vec4 permute(vec4 x){return mod(((x*34.0)+1.0)*x, 289.0);}',
  'vec4 taylorInvSqrt(vec4 r){return 1.79284291400159 - 0.85373472095314 * r;}',
  '',
  'float snoise(vec3 v){',
  '  const vec2  C = vec2(1.0/6.0, 1.0/3.0) ;',
  '  const vec4  D = vec4(0.0, 0.5, 1.0, 2.0);',
  '',
  '  vec3 i  = floor(v + dot(v, C.yyy) );',
  '  vec3 x0 =   v - i + dot(i, C.xxx) ;',
  '',
  '  vec3 g = step(x0.yzx, x0.xyz);',
  '  vec3 l = 1.0 - g;',
  '  vec3 i1 = min( g.xyz, l.zxy );',
  '  vec3 i2 = max( g.xyz, l.zxy );',
  '',
  '  vec3 x1 = x0 - i1 + 1.0 * C.xxx;',
  '  vec3 x2 = x0 - i2 + 2.0 * C.xxx;',
  '  vec3 x3 = x0 - 1. + 3.0 * C.xxx;',
  '',
  '  i = mod(i, 289.0 );',
  '  vec4 p = permute( permute( permute(',
  '           i.z + vec4(0.0, i1.z, i2.z, 1.0 ))',
  '         + i.y + vec4(0.0, i1.y, i2.y, 1.0 ))',
  '         + i.x + vec4(0.0, i1.x, i2.x, 1.0 ));',
  '',
  '  float n_ = 1.0/7.0;',
  '  vec3  ns = n_ * D.wyz - D.xzx;',
  '',
  '  vec4 j = p - 49.0 * floor(p * ns.z *ns.z);',
  '',
  '  vec4 x_ = floor(j * ns.z);',
  '  vec4 y_ = floor(j - 7.0 * x_ );',
  '',
  '  vec4 x = x_ *ns.x + ns.yyyy;',
  '  vec4 y = y_ *ns.x + ns.yyyy;',
  '  vec4 h = 1.0 - abs(x) - abs(y);',
  '',
  '  vec4 b0 = vec4( x.xy, y.xy );',
  '  vec4 b1 = vec4( x.zw, y.zw );',
  '',
  '  vec4 s0 = floor(b0)*2.0 + 1.0;',
  '  vec4 s1 = floor(b1)*2.0 + 1.0;',
  '  vec4 sh = -step(h, vec4(0.0));',
  '',
  '  vec4 a0 = b0.xzyw + s0.xzyw*sh.xxyy ;',
  '  vec4 a1 = b1.xzyw + s1.xzyw*sh.zzww ;',
  '',
  '  vec3 p0 = vec3(a0.xy,h.x);',
  '  vec3 p1 = vec3(a0.zw,h.y);',
  '  vec3 p2 = vec3(a1.xy,h.z);',
  '  vec3 p3 = vec3(a1.zw,h.w);',
  '',
  '  vec4 norm = taylorInvSqrt(vec4(dot(p0,p0), dot(p1,p1), dot(p2, p2), dot(p3,p3)));',
  '  p0 *= norm.x;',
  '  p1 *= norm.y;',
  '  p2 *= norm.z;',
  '  p3 *= norm.w;',
  '',
  '  vec4 m = max(0.6 - vec4(dot(x0,x0), dot(x1,x1), dot(x2,x2), dot(x3,x3)), 0.0);',
  '  m = m * m;',
  '  return 42.0 * dot( m*m, vec4( dot(p0,x0), dot(p1,x1),',
  '                              dot(p2,x2), dot(p3,x3) ) );',
  '}',
  '',
  'mat2 rotate2d(float angle){',
  '  return mat2(cos(angle), -sin(angle), sin(angle), cos(angle));',
  '}',
  '',
  'float fbm(vec3 p) {',
  '  float value = 0.0;',
  '  float amplitude = 0.5;',
  '  float frequency = 1.0;',
  '  for(int i = 0; i < 4; i++) {',
  '    value += amplitude * snoise(p * frequency);',
  '    frequency *= 2.0;',
  '    amplitude *= 0.5;',
  '  }',
  '  return value;',
  '}',
  '',
  'float ridgedNoise(vec3 p) {',
  '  return 1.0 - abs(snoise(p));',
  '}',
  ''
].join('\n')

export const fragmentShaderPresets = {
  default: [
    '// Use the base material color',
    ''
  ].join('\n'),
  fresnel_rim: [
    '// Fresnel rim lighting',
    'vec3 viewDirection = normalize(cameraPosition - vWorldPosition);',
    'float fresnel = 1.0 - abs(dot(viewDirection, vNormal));',
    'fresnel = pow(fresnel, 3.0);',
    'diffuseColor.rgb = mix(diffuseColor.rgb, uFresnelColor, fresnel * uFresnelIntensity);'
  ].join('\n'),
  fresnel_glow: [
    '// Glowing Fresnel effect',
    'vec3 viewDirection = normalize(cameraPosition - vWorldPosition);',
    'float fresnel = 1.0 - abs(dot(viewDirection, vNormal));',
    'fresnel = pow(fresnel, 2.0);',
    'diffuseColor.rgb += uFresnelColor * fresnel * uFresnelIntensity * 1.5;'
  ].join('\n'),
  fresnel_animated: [
    '// Animated Fresnel rim',
    'vec3 viewDirection = normalize(cameraPosition - vWorldPosition);',
    'float fresnel = 1.0 - abs(dot(viewDirection, vNormal));',
    'fresnel = pow(fresnel, 3.0);',
    'float pulse = sin(uTime * 2.0) * 0.5 + 0.5;',
    'vec3 animatedColor = uFresnelColor * (0.8 + pulse * 0.4);',
    'diffuseColor.rgb = mix(diffuseColor.rgb, animatedColor, fresnel * uFresnelIntensity);'
  ].join('\n'),
  iridescent: [
    '// Oil slick iridescence',
    'vec3 viewDirection = normalize(cameraPosition - vWorldPosition);',
    'float fresnel = 1.0 - abs(dot(viewDirection, vNormal));',
    'float iridescence = fresnel * 0.5 + snoise(vWorldPosition * 2.0) * 0.2;',
    'iridescence = fract(iridescence * 2.0 + uTime * 0.2);',
    'vec3 iridColor = vec3(',
    '  sin(iridescence * 6.28318) * 0.3 + 0.7,',
    '  sin(iridescence * 6.28318 + 2.0944) * 0.3 + 0.7,',
    '  sin(iridescence * 6.28318 + 4.18879) * 0.3 + 0.7',
    ');',
    'diffuseColor.rgb = mix(diffuseColor.rgb, diffuseColor.rgb * iridColor, uFresnelIntensity * 0.6);'
  ].join('\n'),
  holographic: [
    '// Holographic shimmer',
    'vec3 viewDirection = normalize(cameraPosition - vWorldPosition);',
    'float fresnel = 1.0 - abs(dot(viewDirection, vNormal));',
    'vec3 holoPos = vWorldPosition * 5.0 + uTime * 0.5;',
    'float holo = snoise(holoPos) * 0.3 + snoise(holoPos * 2.0) * 0.15;',
    'holo = fract((fresnel * 0.5 + holo) * 3.0);',
    'vec3 rainbow = vec3(',
    '  abs(holo * 6.0 - 3.0) - 1.0,',
    '  2.0 - abs(holo * 6.0 - 2.0),',
    '  2.0 - abs(holo * 6.0 - 4.0)',
    ');',
    'rainbow = clamp(rainbow, 0.0, 1.0);',
    'rainbow = rainbow * 0.4 + 0.6;',
    'diffuseColor.rgb = mix(diffuseColor.rgb, diffuseColor.rgb * rainbow, uFresnelIntensity * 0.5);'
  ].join('\n'),
  pearlescent: [
    '// Pearlescent/soap bubble effect',
    'vec3 viewDirection = normalize(cameraPosition - vWorldPosition);',
    'float fresnel = abs(dot(viewDirection, vNormal));',
    'fresnel = pow(1.0 - fresnel, 2.0);',
    'float shift = fresnel * 3.0 + snoise(vWorldPosition * 3.0) * 0.5;',
    'vec3 color1 = vec3(1.0, 0.7, 0.9);',
    'vec3 color2 = vec3(0.6, 0.9, 1.0);',
    'vec3 color3 = vec3(0.9, 1.0, 0.7);',
    'vec3 pearlColor = mix(color1, color2, fract(shift));',
    'pearlColor = mix(pearlColor, color3, fract(shift + 0.33));',
    'diffuseColor.rgb = mix(diffuseColor.rgb, pearlColor, fresnel * uFresnelIntensity);'
  ].join('\n'),
  chromatic: [
    '// Chromatic aberration effect',
    'vec3 viewDirection = normalize(cameraPosition - vWorldPosition);',
    'float fresnel = 1.0 - abs(dot(viewDirection, vNormal));',
    'float offset = fresnel * 0.1 + snoise(vWorldPosition * 5.0 + uTime * 0.3) * 0.05;',
    'vec3 r = uFresnelColor * (1.0 + offset);',
    'vec3 g = uFresnelColor * (1.0);',
    'vec3 b = uFresnelColor * (1.0 - offset);',
    'vec3 chromatic = vec3(r.r, g.g, b.b);',
    'diffuseColor.rgb = mix(diffuseColor.rgb, chromatic, fresnel * uFresnelIntensity);'
  ].join('\n'),
  ambient_occlusion: [
    '// Ambient occlusion based on surface curvature',
    'float ao = 0.0;',
    'vec3 samplePos = vWorldPosition * 1.5;',
    'for(int i = 0; i < 4; i++) {',
    '  float offset = float(i) * 0.15;',
    '  ao += abs(snoise(samplePos + vNormal * offset));',
    '}',
    'ao = ao * 0.25;',
    'ao = 1.0 - (ao * uFresnelIntensity * 0.5);',
    'ao = clamp(ao, 0.5, 1.0);',
    'diffuseColor.rgb *= ao;'
  ].join('\n'),
  cavity: [
    '// Cavity/crevice darkening',
    'vec3 viewDirection = normalize(cameraPosition - vWorldPosition);',
    'float cavity = abs(snoise(vWorldPosition * 2.0)) * 0.2 + 0.8;',
    'float edge = 1.0 - abs(dot(viewDirection, vNormal));',
    'edge = pow(edge, 3.0);',
    'float darkening = mix(cavity, 1.0, edge);',
    'darkening = clamp(darkening, 0.7, 1.0);',
    'diffuseColor.rgb *= mix(1.0, darkening, uFresnelIntensity);'
  ].join('\n'),
  curvature: [
    '// Curvature-based shading',
    'vec3 p = vWorldPosition * 2.5;',
    'float curve = abs(snoise(p + vNormal * 0.08) - snoise(p - vNormal * 0.08));',
    'curve = curve * 0.2 + 0.9;',
    'curve = clamp(curve, 0.8, 1.1);',
    'diffuseColor.rgb *= mix(1.0, curve, uFresnelIntensity);'
  ].join('\n')
}

export const shaderPresets = {
  classic: [
    'vec3 noisePos = vec3(pos.x * noiseFreq + uTime * uAnimationSpeed, pos.y * noiseFreq, pos.z * noiseFreq);',
    'float noise = snoise(noisePos);',
    'pos += normal * noise * noiseAmp;'
  ].join('\n'),
  twister: [
    'float twist = pos.y * 2.0 + uTime * uAnimationSpeed;',
    'vec2 rotatedXZ = rotate2d(twist) * pos.xz;',
    'vec3 twistedPos = vec3(rotatedXZ.x, pos.y, rotatedXZ.y);',
    'vec3 noisePos = twistedPos * noiseFreq;',
    'float noise = snoise(noisePos + uTime * uAnimationSpeed * 0.5);',
    'pos += normal * noise * noiseAmp;'
  ].join('\n'),
  traveling_waves: [
    '// Create wave that travels from pole to pole without twist',
    'float wave = mod(pos.y * noiseFreq * 3.0 + uTime * uAnimationSpeed * 2.0, 2.0);',
    '// Triangle wave pattern',
    'float displacement = 1.0 - abs(wave - 1.0);',
    '',
    'pos += normal * displacement * noiseAmp;'
  ].join('\n'),
  bubbles: [
    'vec3 noisePos = pos * noiseFreq + uTime * uAnimationSpeed * 0.3;',
    'float noise = abs(snoise(noisePos)) * 0.5 + abs(snoise(noisePos * 2.0)) * 0.25 + abs(snoise(noisePos * 4.0)) * 0.125;',
    'pos += normal * noise * noiseAmp;'
  ].join('\n'),
  waves: [
    'float wave1 = sin(pos.x * noiseFreq * 2.0 + uTime * uAnimationSpeed * 2.0) * 0.5;',
    'float wave2 = sin(pos.y * noiseFreq * 2.0 + uTime * uAnimationSpeed * 1.5) * 0.3;',
    'float wave3 = sin(pos.z * noiseFreq * 2.0 + uTime * uAnimationSpeed * 2.5) * 0.2;',
    'vec3 noisePos = pos * noiseFreq + vec3(wave1, wave2, wave3);',
    'float noise = snoise(noisePos + uTime * uAnimationSpeed * 0.5);',
    'pos += normal * (noise * 0.5 + wave1 + wave2 + wave3) * noiseAmp;'
  ].join('\n'),
  spiky: [
    'vec3 noisePos = pos * noiseFreq + uTime * uAnimationSpeed * 0.2;',
    'float noise = ridgedNoise(noisePos) * 1.5;',
    'noise += ridgedNoise(noisePos * 2.0) * 0.5;',
    'pos += normal * noise * noiseAmp;'
  ].join('\n'),
  turbulence: [
    'vec3 noisePos = pos * noiseFreq;',
    'float turbulence = fbm(noisePos + uTime * uAnimationSpeed);',
    'vec3 offset = vec3(',
    '  snoise(noisePos + vec3(0.0, uTime * uAnimationSpeed, 0.0)),',
    '  snoise(noisePos + vec3(uTime * uAnimationSpeed, 0.0, 0.0)),',
    '  snoise(noisePos + vec3(0.0, 0.0, uTime * uAnimationSpeed))',
    ');',
    'pos += normal * turbulence * noiseAmp + offset * noiseAmp * 0.3;'
  ].join('\n')
}
