// Shader functions and presets

export const shaderFunctions = [
  '// Simplex 3D Noise',
  '// https://gist.github.com/patriciogonzalezvivo/670c22f3966e662d2f83',
  'vec4 permute(vec4 x){return mod(((x*34.0)+1.0)*x, 289.0);}',
  'vec4 taylorInvSqrt(vec4 r){return 1.79284291400159 - 0.85373472095314 * r;}',
  '',
  'float snoise(vec3 v){',
  '  const vec2  C = vec2(1.0/6.0, 1.0/3.0) ;',
  '  const vec4  D = vec4(0.0, 0.5, 1.0, 2.0);',
  '',
  '  vec3 i  = floor(v + dot(v, C.yyy) );',
  '  vec3 x0 =   v - i + dot(i, C.xxx) ;',
  '',
  '  vec3 g = step(x0.yzx, x0.xyz);',
  '  vec3 l = 1.0 - g;',
  '  vec3 i1 = min( g.xyz, l.zxy );',
  '  vec3 i2 = max( g.xyz, l.zxy );',
  '',
  '  vec3 x1 = x0 - i1 + 1.0 * C.xxx;',
  '  vec3 x2 = x0 - i2 + 2.0 * C.xxx;',
  '  vec3 x3 = x0 - 1. + 3.0 * C.xxx;',
  '',
  '  i = mod(i, 289.0 );',
  '  vec4 p = permute( permute( permute(',
  '           i.z + vec4(0.0, i1.z, i2.z, 1.0 ))',
  '         + i.y + vec4(0.0, i1.y, i2.y, 1.0 ))',
  '         + i.x + vec4(0.0, i1.x, i2.x, 1.0 ));',
  '',
  '  float n_ = 1.0/7.0;',
  '  vec3  ns = n_ * D.wyz - D.xzx;',
  '',
  '  vec4 j = p - 49.0 * floor(p * ns.z *ns.z);',
  '',
  '  vec4 x_ = floor(j * ns.z);',
  '  vec4 y_ = floor(j - 7.0 * x_ );',
  '',
  '  vec4 x = x_ *ns.x + ns.yyyy;',
  '  vec4 y = y_ *ns.x + ns.yyyy;',
  '  vec4 h = 1.0 - abs(x) - abs(y);',
  '',
  '  vec4 b0 = vec4( x.xy, y.xy );',
  '  vec4 b1 = vec4( x.zw, y.zw );',
  '',
  '  vec4 s0 = floor(b0)*2.0 + 1.0;',
  '  vec4 s1 = floor(b1)*2.0 + 1.0;',
  '  vec4 sh = -step(h, vec4(0.0));',
  '',
  '  vec4 a0 = b0.xzyw + s0.xzyw*sh.xxyy ;',
  '  vec4 a1 = b1.xzyw + s1.xzyw*sh.zzww ;',
  '',
  '  vec3 p0 = vec3(a0.xy,h.x);',
  '  vec3 p1 = vec3(a0.zw,h.y);',
  '  vec3 p2 = vec3(a1.xy,h.z);',
  '  vec3 p3 = vec3(a1.zw,h.w);',
  '',
  '  vec4 norm = taylorInvSqrt(vec4(dot(p0,p0), dot(p1,p1), dot(p2, p2), dot(p3,p3)));',
  '  p0 *= norm.x;',
  '  p1 *= norm.y;',
  '  p2 *= norm.z;',
  '  p3 *= norm.w;',
  '',
  '  vec4 m = max(0.6 - vec4(dot(x0,x0), dot(x1,x1), dot(x2,x2), dot(x3,x3)), 0.0);',
  '  m = m * m;',
  '  return 42.0 * dot( m*m, vec4( dot(p0,x0), dot(p1,x1),',
  '                              dot(p2,x2), dot(p3,x3) ) );',
  '}',
  '',
  'mat2 rotate2d(float angle){',
  '  return mat2(cos(angle), -sin(angle), sin(angle), cos(angle));',
  '}',
  '',
  'float fbm(vec3 p) {',
  '  float value = 0.0;',
  '  float amplitude = 0.5;',
  '  float frequency = 1.0;',
  '  for(int i = 0; i < 4; i++) {',
  '    value += amplitude * snoise(p * frequency);',
  '    frequency *= 2.0;',
  '    amplitude *= 0.5;',
  '  }',
  '  return value;',
  '}',
  '',
  'float ridgedNoise(vec3 p) {',
  '  return 1.0 - abs(snoise(p));',
  '}',
  ''
].join('\n')

export const fragmentShaderPresets = {
  default: [
    '// Use the base material color',
    ''
  ].join('\n'),
  fresnel_rim: [
    '// Fresnel rim lighting',
    'vec3 viewDirection = normalize(cameraPosition - vWorldPosition);',
    'vec3 displacedNorm = normalize(vDisplacedNormal);',
    'float fresnel = 1.0 - abs(dot(viewDirection, displacedNorm));',
    'fresnel = pow(fresnel, 3.0);',
    'diffuseColor.rgb = mix(diffuseColor.rgb, uFresnelColor, fresnel * uFresnelIntensity);'
  ].join('\n'),
  fresnel_glow: [
    '// Glowing Fresnel effect',
    'vec3 viewDirection = normalize(cameraPosition - vWorldPosition);',
    'vec3 displacedNorm = normalize(vDisplacedNormal);',
    'float fresnel = 1.0 - abs(dot(viewDirection, displacedNorm));',
    'fresnel = pow(fresnel, 2.0);',
    'diffuseColor.rgb += uFresnelColor * fresnel * uFresnelIntensity * 1.5;'
  ].join('\n'),
  fresnel_animated: [
    '// Animated Fresnel rim',
    'vec3 viewDirection = normalize(cameraPosition - vWorldPosition);',
    'vec3 displacedNorm = normalize(vDisplacedNormal);',
    'float fresnel = 1.0 - abs(dot(viewDirection, displacedNorm));',
    'fresnel = pow(fresnel, 3.0);',
    'float pulse = sin(uTime * 2.0) * 0.5 + 0.5;',
    'vec3 animatedColor = uFresnelColor * (0.8 + pulse * 0.4);',
    'diffuseColor.rgb = mix(diffuseColor.rgb, animatedColor, fresnel * uFresnelIntensity);'
  ].join('\n'),
  iridescent: [
    '// Oil slick iridescence based on displacement',
    'vec3 viewDirection = normalize(cameraPosition - vWorldPosition);',
    'vec3 displacedNorm = normalize(vDisplacedNormal);',
    'float fresnel = 1.0 - abs(dot(viewDirection, displacedNorm));',
    '',
    '// Use displacement derivatives to create interference patterns',
    'float dx = dFdx(vDistanceFromCenter);',
    'float dy = dFdy(vDistanceFromCenter);',
    'float variation = length(vec2(dx, dy)) * 10.0;',
    '',
    '// Base sphere radius',
    'float baseRadius = 1.5;',
    'float displacement = vDistanceFromCenter - baseRadius;',
    '',
    '// Combine fresnel, displacement, and variation for color bands',
    'float iridescence = fresnel * 0.5 + displacement * 2.0 + variation;',
    'iridescence = fract(iridescence * 2.0 + uTime * 0.2);',
    'vec3 iridColor = vec3(',
    '  sin(iridescence * 6.28318) * 0.3 + 0.7,',
    '  sin(iridescence * 6.28318 + 2.0944) * 0.3 + 0.7,',
    '  sin(iridescence * 6.28318 + 4.18879) * 0.3 + 0.7',
    ');',
    'diffuseColor.rgb = mix(diffuseColor.rgb, diffuseColor.rgb * iridColor, uFresnelIntensity * 0.6);'
  ].join('\n'),
  holographic: [
    '// Holographic shimmer based on displacement',
    'vec3 viewDirection = normalize(cameraPosition - vWorldPosition);',
    'vec3 displacedNorm = normalize(vDisplacedNormal);',
    'float fresnel = 1.0 - abs(dot(viewDirection, displacedNorm));',
    '',
    '// Use displacement derivatives for holographic patterns',
    'float dx = dFdx(vDistanceFromCenter);',
    'float dy = dFdy(vDistanceFromCenter);',
    'float gradientAngle = atan(dy, dx);',
    '',
    '// Base sphere radius',
    'float baseRadius = 1.5;',
    'float displacement = vDistanceFromCenter - baseRadius;',
    '',
    '// Create holographic bands from displacement and gradient',
    'float holo = displacement * 3.0 + gradientAngle * 2.0 + length(vec2(dx, dy)) * 8.0;',
    'holo = fract((fresnel * 0.5 + holo + uTime * 0.3) * 2.0);',
    'vec3 rainbow = vec3(',
    '  abs(holo * 6.0 - 3.0) - 1.0,',
    '  2.0 - abs(holo * 6.0 - 2.0),',
    '  2.0 - abs(holo * 6.0 - 4.0)',
    ');',
    'rainbow = clamp(rainbow, 0.0, 1.0);',
    'rainbow = rainbow * 0.4 + 0.6;',
    'diffuseColor.rgb = mix(diffuseColor.rgb, diffuseColor.rgb * rainbow, uFresnelIntensity * 0.5);'
  ].join('\n'),
  pearlescent: [
    '// Pearlescent/soap bubble effect based on displacement',
    'vec3 viewDirection = normalize(cameraPosition - vWorldPosition);',
    'vec3 displacedNorm = normalize(vDisplacedNormal);',
    'float fresnel = abs(dot(viewDirection, displacedNorm));',
    'fresnel = pow(1.0 - fresnel, 2.0);',
    '',
    '// Use displacement and its gradient for pearl effect',
    'float dx = dFdx(vDistanceFromCenter);',
    'float dy = dFdy(vDistanceFromCenter);',
    'float variation = length(vec2(dx, dy)) * 5.0;',
    '',
    '// Base sphere radius',
    'float baseRadius = 1.5;',
    'float displacement = vDistanceFromCenter - baseRadius;',
    '',
    '// Create color shift based on displacement thickness illusion',
    'float shift = fresnel * 3.0 + displacement * 4.0 + variation;',
    'vec3 color1 = vec3(1.0, 0.7, 0.9);',
    'vec3 color2 = vec3(0.6, 0.9, 1.0);',
    'vec3 color3 = vec3(0.9, 1.0, 0.7);',
    'vec3 pearlColor = mix(color1, color2, fract(shift));',
    'pearlColor = mix(pearlColor, color3, fract(shift + 0.33));',
    'diffuseColor.rgb = mix(diffuseColor.rgb, pearlColor, fresnel * uFresnelIntensity);'
  ].join('\n'),
  chromatic: [
    '// Chromatic aberration effect based on displacement',
    'vec3 viewDirection = normalize(cameraPosition - vWorldPosition);',
    'vec3 displacedNorm = normalize(vDisplacedNormal);',
    'float fresnel = 1.0 - abs(dot(viewDirection, displacedNorm));',
    'fresnel = pow(fresnel, 2.0);',
    '',
    '// Use displacement derivatives for chromatic dispersion',
    'float dx = dFdx(vDistanceFromCenter);',
    'float dy = dFdy(vDistanceFromCenter);',
    'float variation = length(vec2(dx, dy)) * 10.0;',
    '',
    '// Base sphere radius',
    'float baseRadius = 1.5;',
    'float displacement = vDistanceFromCenter - baseRadius;',
    '',
    '// Create RGB channel separation using rim color',
    'float aberration = (fresnel + variation) * uFresnelIntensity;',
    '',
    '// Add color fringing to edges based on rim color',
    'vec3 chromaColor = uFresnelColor * aberration;',
    'diffuseColor.rgb += chromaColor * 0.5;'
  ].join('\n'),
  ambient_occlusion: [
    '// Ambient occlusion using screen-space derivatives to detect concavity',
    '// Use derivatives to detect how displacement changes across the surface',
    'float dx = dFdx(vDistanceFromCenter);',
    'float dy = dFdy(vDistanceFromCenter);',
    '',
    '// Calculate local curvature',
    'float curvature = length(vec2(dx, dy)) * 30.0;',
    '',
    '// Detect if this is a valley (concave) or peak (convex)',
    '// Valleys have higher curvature and lower distance from center relative to base sphere',
    'float baseRadius = 1.5; // Sphere radius',
    'float displacement = vDistanceFromCenter - baseRadius;',
    '',
    '// AO is stronger in valleys (negative displacement with high curvature)',
    'float cavity = smoothstep(-0.3, 0.0, -displacement) * curvature;',
    'float ao = 1.0 - (cavity * uFresnelIntensity * 0.5);',
    'ao = clamp(ao, 0.4, 1.0);',
    '',
    'diffuseColor.rgb *= ao;'
  ].join('\n'),
  cavity: [
    '// Cavity/crevice darkening using displacement derivatives',
    'vec3 viewDirection = normalize(cameraPosition - vWorldPosition);',
    'vec3 displacedNorm = normalize(vDisplacedNormal);',
    '',
    '// Calculate how rapidly displacement changes',
    'float dx = dFdx(vDistanceFromCenter);',
    'float dy = dFdy(vDistanceFromCenter);',
    'float gradientMagnitude = length(vec2(dx, dy)) * 20.0;',
    '',
    '// Base sphere radius',
    'float baseRadius = 1.5;',
    'float displacement = vDistanceFromCenter - baseRadius;',
    '',
    '// Cavities are valleys with high gradient change',
    'float cavityDetection = smoothstep(-0.2, 0.0, -displacement) * gradientMagnitude;',
    '',
    '// Add edge darkening for extra depth',
    'float edge = 1.0 - abs(dot(viewDirection, displacedNorm));',
    'edge = pow(edge, 2.0) * 0.3;',
    '',
    'float darkening = 1.0 - ((cavityDetection + edge) * uFresnelIntensity * 0.4);',
    'darkening = clamp(darkening, 0.5, 1.0);',
    'diffuseColor.rgb *= darkening;'
  ].join('\n'),
  curvature: [
    '// Curvature-based shading using second derivatives',
    '// Calculate rate of change of displacement',
    'float dx = dFdx(vDistanceFromCenter);',
    'float dy = dFdy(vDistanceFromCenter);',
    '',
    '// Approximate second derivative (curvature)',
    'float dxx = dFdx(dx);',
    'float dyy = dFdy(dy);',
    'float curvature = abs(dxx + dyy) * 15.0;',
    '',
    '// High curvature means the surface is bending sharply',
    '// Make these areas slightly brighter or darker based on sign',
    'float curve = 1.0 + (curvature - 0.5) * uFresnelIntensity * 0.3;',
    'curve = clamp(curve, 0.7, 1.3);',
    'diffuseColor.rgb *= curve;'
  ].join('\n'),
  displacement_peaks: [
    '// Highlight extreme displacement points',
    'float threshold = 1.5 + uFresnelIntensity * 0.3;',
    'float dist = vDistanceFromCenter;',
    'float highlight = smoothstep(threshold - 0.1, threshold + 0.1, dist);',
    'diffuseColor.rgb = mix(diffuseColor.rgb, uFresnelColor, highlight);'
  ].join('\n')
}

export const shaderPresets = {
  classic: [
    'vec3 noisePos = vec3(pos.x * noiseFreq + uTime * uAnimationSpeed, pos.y * noiseFreq, pos.z * noiseFreq);',
    'float noise = snoise(noisePos);',
    'pos += normal * noise * noiseAmp;'
  ].join('\n'),
  twister: [
    'float twist = pos.y * 2.0 + uTime * uAnimationSpeed;',
    'vec2 rotatedXZ = rotate2d(twist) * pos.xz;',
    'vec3 twistedPos = vec3(rotatedXZ.x, pos.y, rotatedXZ.y);',
    'vec3 noisePos = twistedPos * noiseFreq;',
    'float noise = snoise(noisePos + uTime * uAnimationSpeed * 0.5);',
    'pos += normal * noise * noiseAmp;'
  ].join('\n'),
  traveling_waves: [
    '// Create wave that travels from pole to pole without twist',
    'float wave = mod(pos.y * noiseFreq * 3.0 + uTime * uAnimationSpeed * 2.0, 2.0);',
    '// Triangle wave pattern',
    'float displacement = 1.0 - abs(wave - 1.0);',
    '',
    'pos += normal * displacement * noiseAmp;'
  ].join('\n'),
  bubbles: [
    'vec3 noisePos = pos * noiseFreq + uTime * uAnimationSpeed * 0.3;',
    'float noise = abs(snoise(noisePos)) * 0.5 + abs(snoise(noisePos * 2.0)) * 0.25 + abs(snoise(noisePos * 4.0)) * 0.125;',
    'pos += normal * noise * noiseAmp;'
  ].join('\n'),
  waves: [
    'float wave1 = sin(pos.x * noiseFreq * 2.0 + uTime * uAnimationSpeed * 2.0) * 0.5;',
    'float wave2 = sin(pos.y * noiseFreq * 2.0 + uTime * uAnimationSpeed * 1.5) * 0.3;',
    'float wave3 = sin(pos.z * noiseFreq * 2.0 + uTime * uAnimationSpeed * 2.5) * 0.2;',
    'vec3 noisePos = pos * noiseFreq + vec3(wave1, wave2, wave3);',
    'float noise = snoise(noisePos + uTime * uAnimationSpeed * 0.5);',
    'pos += normal * (noise * 0.5 + wave1 + wave2 + wave3) * noiseAmp;'
  ].join('\n'),
  spiky: [
    'vec3 noisePos = pos * noiseFreq + uTime * uAnimationSpeed * 0.2;',
    'float noise = ridgedNoise(noisePos) * 1.5;',
    'noise += ridgedNoise(noisePos * 2.0) * 0.5;',
    'pos += normal * noise * noiseAmp;'
  ].join('\n'),
  turbulence: [
    'vec3 noisePos = pos * noiseFreq;',
    'float turbulence = fbm(noisePos + uTime * uAnimationSpeed);',
    'vec3 offset = vec3(',
    '  snoise(noisePos + vec3(0.0, uTime * uAnimationSpeed, 0.0)),',
    '  snoise(noisePos + vec3(uTime * uAnimationSpeed, 0.0, 0.0)),',
    '  snoise(noisePos + vec3(0.0, 0.0, uTime * uAnimationSpeed))',
    ');',
    'pos += normal * turbulence * noiseAmp + offset * noiseAmp * 0.3;'
  ].join('\n')
}
